name: base  # Tên của môi trường Conda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - flake8
  - pytest
  - pytest-cov
  - pip
  - pip:
      - requests  # Cài đặt thư viện từ PyPI
